Task conexion front
ylatorre/greenshop pull request #26
Opened 2024-02-26 10:28 UTC by AlexChabriel

2024-02-26 10:36 UTC, ylatorre requested changes

2024-02-26 10:36 UTC, ylatorre commented on templates/lost_pass_word/index.html.twig
> +<style>
Le code css dans le fichier assets/styles/app.css

2024-02-26 10:36 UTC, ylatorre commented on templates/registration/register.html.twig
> +<script>
Meme chose pour le js dans le fichier assets/app.js

2024-02-26 10:36 UTC, ylatorre commented on templates/security/login.html.twig
> +<style>
Meme chose ici le css dans le app.css

2024-02-27 07:51 UTC, AlexChabriel commented on templates/registration/register.html.twig
> +<script>
c'est fait

2024-02-27 08:06 UTC, ylatorre requested changes
Ou est le css ?

2024-02-27 08:20 UTC, ylatorre approved these changes

2024-02-27 08:20 UTC, merged